name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "**.rs"
      - "**.proto"
      - "**.toml"
      - "**.lock"
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rs"
      - "**.proto"
      - "**.toml"
      - "**.lock"
      - ".github/workflows/*.yml"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  pre_ci:
    uses: SDLMoe/.github/.github/workflows/pre_ci.yml@master

  check:
    name: Check Formatting
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Setup protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run Rustfmt
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy --all -- -D warnings

  security_audit:
    name: cargo audit
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
